### ISSUE TITLE
Tab item with long title

### ISSUE THREAD

**Issue by kockok** [torgeadelin/react-native-animated-nav-tab-bar#31]
I have two concerns for the layout with reference to the screen cap.
![Screenshot 2020-08-07 at 12 47 27 AM](https://user-images.githubusercontent.com/232541/89559269-0583f380-d848-11ea-9e5b-74bd21cd4914.png)

1. How to adjust the space between the text and the icon?
2. How to add more padding for the title ending by squeezing the space between the subsequent icons

**Comment by torgeadelin** [comment]
At the moment there is no posibility to adjust the space between the text and icon. In order to change the dot(backgorund) size, use the `dotSize` prop (look at the docs). Let me know if that fixes your issue.

PS, In general you'd try to avoid long text inside a tab bar.. Try to keep it as low as 1 word. This will ensure that your UI is consistent across multiple devices.

**Comment by kockok** [comment]
I've tried `dotSize` but it didn't help.
However, I do think that a mere five word title isn't that inappropriate as there's still plenty of space left behind.
