### ISSUE TITLE
Bottom tabs overlay

### ISSUE THREAD

**Issue by leon2835** [torgeadelin/react-native-animated-nav-tab-bar#33]
Hi and thanks for the library, currently i'm using version 3.0.3 and followed the example code that provided, and this happened.
(Currently temp walkaround which is head to node_modules/react-native-aniamted-nav-tab-bar/src/TabBarElement, change the overlayStyle to flex:0.1 & current screen to flex:0.9 will solved the problem.)
![Screenshot_1597215426](https://user-images.githubusercontent.com/19604759/89984561-2b782080-dcac-11ea-829c-88186758203a.png)

**Comment by torgeadelin** [comment]
I can see the issue, but have you considered displaying just the tab icon even when it's selected? It will look crowded even with the additional space around if you keep the text. Look at the docs, there's a way tou can configure that.

I will try to add some more configuration to enable spacing customisations. Although, I kind of purposely forces the current styles so that good UI/UX will be enforced.

**Comment by torgeadelin** [comment]
There's also a `dotSize` prop which adjusts the size of the selected tab. Did you try that?

**Comment by leon2835** [comment]
@torgeadelin  Alright dude, thanks for the dotSize, it's managed to look better now.
![Screenshot_1597378591](https://user-images.githubusercontent.com/19604759/90213303-09a3a880-de28-11ea-856b-4cf0b1716e15.png)

**Comment by torgeadelin** [comment]
Closing for now.
Will try to add even more customisation in the future.
Thanks!
