### ISSUE TITLE
How to decrease padding between left side to icon and rightside to text and increase the tab height

### ISSUE THREAD

**Issue by saikiranoptisol** [torgeadelin/react-native-animated-nav-tab-bar#4]
i was trying to decrease padding between the icon and left side of icon and text and right side of text and tring to increase the height of tab which is a bit difficult to achieve. tabBarOptions is not at all working. 

 const HomeScreenTab = createMaterialTopTabNavigator(
          {
              Home: HomeStack,
              Aiyoooo: DiscoverStack,
              Images: ImagesStack,
              Profie: ProfileStack,
          },{
            tabBarOptions: {
                labelStyle: {
                  padding: 5 
                },
                tabStyle: {
                    height: 90
                },
                iconStyle: {
                    padding: 80,
                },
                swipeEnabled: false,

              },
            tabBarComponent: props => <TabBar
                activeColors={'#fff'} // or activeColors={'#e6b580'}
                activeTabBackgrounds={'#4291E2'} // or activeTabBackgrounds={'#ede7e6'}
                {...props}
            />,
                animationEnabled: false,
                headerMode: "none",
                navigationOptions: {
                gesturesEnabled: false
                }

this is not at all working for me. even the colors are not updating

**Comment by torgeadelin** [comment]
Hi! Yes indeed, the tabBarOptions won’t work in this case as I haven’t linked those properties with the actual component in my implementation. I’m going to add some extra customisations props so you can adjust the design of the tab bar items.

For the colours make sure you have the last version of the package. If still doesn’t work try using activeColor instead of activeColor*s*

I will try to release a new version as soon as I can. 

Thanks!
